-- Supabase Database Schema for Indian Stock Trading AI System
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Predictions Table
CREATE TABLE IF NOT EXISTS predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    ticker TEXT NOT NULL,
    rank INT NOT NULL,
    starting_price FLOAT NOT NULL,
    expected_gain_pct FLOAT NOT NULL,
    target_price FLOAT NOT NULL,
    stop_loss FLOAT NOT NULL,
    confidence_score FLOAT NOT NULL,
    signal_reasons TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, ticker)
);

-- 2. Outcomes Table (Recorded post market-close)
CREATE TABLE IF NOT EXISTS outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    ticker TEXT NOT NULL,
    starting_price FLOAT NOT NULL,
    close_price FLOAT NOT NULL,
    high_price FLOAT NOT NULL,
    low_price FLOAT NOT NULL,
    actual_gain_pct FLOAT NOT NULL,
    max_gain_pct FLOAT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, ticker)
);

-- 3. Model Retraining Audit Log Table
CREATE TABLE IF NOT EXISTS model_retraining_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    samples_count INT NOT NULL,
    mae FLOAT,
    win_rate_pct FLOAT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) or public service policy if needed
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE model_retraining_log ENABLE ROW LEVEL SECURITY;

-- Allow authenticated/service role full access
CREATE POLICY "Service Role Full Access on Predictions" ON predictions FOR ALL USING (true);
CREATE POLICY "Service Role Full Access on Outcomes" ON outcomes FOR ALL USING (true);
CREATE POLICY "Service Role Full Access on Retraining Log" ON model_retraining_log FOR ALL USING (true);
